name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - name: Installing dependencies
      run:  sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run tauri build --verbose
