name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run tauri build --verbose
